### ISSUE TITLE
LD_LIBRARY_PATH issue

### ISSUE THREAD

**Issue by dlaporte** [kcyarn/oobabooga_intel_arc#1]
Thank you for these scripts!  When running run_arc.sh, I got the following error:

OSError: libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory

Adding:

export LD_LIBRARY_PATH=/opt/intel/oneapi/2024.0/lib

to the exports at the top fixed it!

**Comment by kcyarn** [comment]
Good to know! I use oneapi for more than oobabooga, so my oneapi source is in .bashrc and just runs when I open a terminal.

Does running `source /opt/intel/oneapi/setvars.sh` in terminal before starting the script also solve the issue? If it does, it might be better to export servars.sh. From what I understand, that catches more Intel specific libraries.

________________________________
From: David LaPorte ***@***.***>
Sent: Sunday, January 28, 2024 4:21:26 PM
To: kcyarn/oobabooga_intel_arc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [kcyarn/oobabooga_intel_arc] LD_LIBRARY_PATH issue (Issue #1)


Thank you for these scripts! When running run_arc.sh, I got the following error:

OSError: libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory

Adding:

export LD_LIBRARY_PATH=/opt/intel/oneapi/2024.0/lib

to the exports at the top fixed it!

**Comment by dlaporte** [comment]
Yes, sourcing /opt/intel/oneapi/setvars.sh does work and agreed that it seems like a cleaner option.  Thanks!
